version: '3.4'
services:
  nats:
    container_name: nats-container
    image: nats
    networks:
      - network-failure
    restart: always

  nets:
    container_name: nets-container
    image: nats
    networks:
      - network-failure
    restart: always

networks:
  network-failure:
    name: network-failure