version: '3.1'
services:
  webapp:
    image: nginx:latest
    restart: always
    ports:
      - "${PORT:-3002}:80"
    volumes:
      - ./static:/usr/share/nginx/html
    tty: true
    stdin_open: true
