version: '3.1'
services:
  webapp:
    image: nginx:1.20.1
    restart: always
    ports:
      - "${PORT:-3003}:80"
    volumes:
      - ./static:/usr/share/nginx/html
    tty: true
    stdin_open: true
