services:
  test:
    build:
      dockerfile_inline: |
        # Dockerfile
        FROM ubuntu:latest

        RUN apt-get update && \
            apt-get install -y jq && \
            apt-get clean && \
            rm -rf /var/lib/apt/lists/*
    command: ["bash", "-c", "jq --version && echo hello"]