version: '3'
services:
 app:
  image: ${IMAGE:-nats}
  tty: true
  stdin_open: ${BOOLEAN:-true}
  environment:
   - ${ENV:-environment}=value1
   - horsing=around
   - steam=deck
   - rog=ally
   - some=hoopla
   - alien=inv
