services:
  nginx:
    image: nginx:latest
    ports:
      - 8019:80
    volumes:
      - ${WEB_HOME}:/usr/share/nginx/html/
    environment:
     - hello=hi
     - adas=zxc
    env_file:
      - stack.env