version: '3'
services:
 gitlabapp:
  image: ${IMAGE:-registry.gitlab.com/6261998/registry/alpine:latest}
  tty: true
  stdin_open: true
  environment:
   - ${ENV:-default}=deck
   - ${ENV2:-default}=ally
   - ${ENV3:-default}=go
   - lkjk=jlkjlk
   - sdf=xcv
