apiVersion: v1
kind: Namespace
metadata:
  name: kubeprunens
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prune-test-config
  namespace: kubeprunens
data:
  key: value
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prune-test-deployment
  namespace: kubeprunens
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prune-test
  template:
    metadata:
      labels:
        app: prune-test
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
