apiVersion: v1
kind: Namespace
metadata:
  name: kubeprune
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prune-test-deployment
  namespace: kubeprune
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prune-test
  template:
    metadata:
      labels:
        app: prune-test
    spec:
      serviceAccountName: prune-test-sa
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80

