apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats3
  labels:
    app: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - name: nats3
        image: nats
        env:
         - name: branch
           value: main